name: Build and Package

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build_windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller cryptography selenium webdriver_manager

      - name: Build Windows executable
        run: pyinstaller --onefile src/knu_auto_login.py

      - name: Upload Windows artifact
        uses: actions/upload-artifact@v2
        with:
          name: Windows 전용 파일
          path: dist/knu_auto_login.exe

  build_mac:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller cryptography selenium webdriver_manager

      - name: Build macOS executable
        run: pyinstaller --onefile src/knu_auto_login.py

      - name: Upload macOS artifact
        uses: actions/upload-artifact@v2
        with:
          name: macOS 전용 (맥북) 파일
          path: dist/knu_auto_login

  build_linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller cryptography selenium webdriver_manager

      - name: Build Linux executable
        run: pyinstaller --onefile src/knu_auto_login.py

      - name: Upload Linux artifact
        uses: actions/upload-artifact@v2
        with:
          name: Linux 전용 파일
          path: dist/knu_auto_login
